[[addresses]]
addr = "0x9679E26bf0C470521DE83Ad77BB1bf1e7312f739"
name = "DEPLOYER_EOA"
isContract = false

[[addresses]]
addr = "0xc0da02939e1441f497fd74f78ce7decb17b66529"
name = "COMPOUND_GOVERNOR_BRAVO"
isContract = false

[[addresses]]
addr = "0x316f9708bB98af7dA9c68C1C3b5e79039cD336E3"
name = "COMPOUND_CONFIGURATOR"
isContract = false
