name: "Setup Environment"
description: "Set up the pre-compiled environment"

runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache Foundry toolchain
      uses: actions/cache@v2
      with:
        path: ~/.foundry
        key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}
        restore-keys: |
          ${{ runner.os }}-foundry-

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly-e52076714ace23c7a68e14f0048a40be3c6c8f0b

    - name: Clean Contracts
      run: forge clean
      shell: bash

    - name: Compile Contracts
      run: forge build
      shell: bash
