currentTaskIndex = 0

[runFlags]
debug = false
doMock = true
doBuild = true
doSimulate = true
doValidate = true
doPrint = true

[task]
safeConfigChange = false
safeOwnersChange = false
safeAddressString = "SystemConfigOwner"
allowedStorageAccesses = ["SystemConfigProxy"]
authorizedDelegateCalls = ["SYSTEM_CONFIG_LOGIC"]

[[mainnet]]
safeNonce = 67

[[mainnet.l2chains]]
name = "Orderly"
chain_id = 291

[[mainnet.l2chains]]
name = "Metal"
chain_id = 1750

[[mainnet]]
safeNonce = 15

[[mainnet.l2chains]]
name = "OP Mainnet"
chain_id = 1740

[[mainnet.l2chains]]
name = "Base"
chain_id = 919

[[sepolia]]
safeNonce = 10

[[sepolia.l2chains]]
name = "Mode Testnet"
chain_id = 919

[[sepolia.l2chains]]
name = "Metal L2 Testnet"
chain_id = 1740

[[sepolia.l2chains]]
name = "Zora Sepolia Testnet"
chain_id = 999999999
