safeConfigChange = false
safeOwnersChange = false
safeAddressString = "SystemConfigOwner"
allowedStorageAccesses = ["SystemConfigProxy"]

[mainnet.task1]
safeNonce = 10

[[mainnet.task1.l2chains]]
name = "OP Mainnet"
chain_id = 10

[[mainnet.task1.l2chains]]
name = "Base"
chain_id = 8453

[mainnet.task2]
safeNonce = 15

[[mainnet.task2.l2chains]]
name = "OP Mainnet"
chain_id = 10

[[mainnet.task2.l2chains]]
name = "Base"
chain_id = 8453

[sepolia.task1]
safeNonce = 20

[[sepolia.task1.l2chains]]
name = "OP Sepolia Testnet"
chain_id = 11155420

[[sepolia.task1.l2chains]]
name = "Base Sepolia Testnet"
chain_id = 84532
