[task]
safeConfigChange = false
safeOwnersChange = false
safeAddressString = "SystemConfigOwner"
allowedStorageAccesses = ["SystemConfigProxy"]
mainnetTask = {safeNonce = 10, networks = [{l2ChainId = 291, networkName = "Orderly"}, {l2ChainId = 1750, networkName = "Orderly"}] }
sepoliaTask = { safeNonce = 20, networks = [{l2ChainId = 1740, networkName = "Metal Sepolia Testnet"}] }

[[chains]]
  name = "Orderly"
  chainId = 291

[[chains]]
  name = "Metal"
  chainId = 1750
