[task]
safeConfigChange = false
safeOwnersChange = false
safeAddressString = "SystemConfigOwner"
allowedStorageAccesses = ["SystemConfigProxy"]
authorizedDelegateCalls = ["SYSTEM_CONFIG_LOGIC"]

[mainnet.task1]
safeNonce = 67

[[mainnet.task1.l2chains]]
name = "Orderly"
chain_id = 291

[[mainnet.task1.l2chains]]
name = "Metal"
chain_id = 1750

[mainnet.task2]
safeNonce = 15

[[mainnet.task2.l2chains]]
name = "OP Mainnet"
chain_id = 1740

[[mainnet.task2.l2chains]]
name = "Base"
chain_id = 919

[sepolia.task1]
safeNonce = 10

[[sepolia.task1.l2chains]]
name = "Mode Testnet"
chain_id = 919

[[sepolia.task1.l2chains]]
name = "Metal L2 Testnet"
chain_id = 1740

[[sepolia.task1.l2chains]]
name = "Zora Sepolia Testnet"
chain_id = 999999999