[task]
safeConfigChange = false
safeOwnersChange = false
safeAddressString = "ProxyAdminOwner"
allowedStorageAccesses = ["SystemConfigProxy"]
mainnetTask = {safeNonce = 10, networks = [{l2ChainId = 7777777, networkName = "Zora"}, {l2ChainId = 10, networkName = "OP Mainnet"}] }
sepoliaTask = { safeNonce = 20, networks = [{l2ChainId = 999999999, networkName = "Zora Sepolia Testnet"}, {l2ChainId = 11155420, networkName = "OP Sepolia Testnet"}] }

[[chains]]
  name = "OP Mainnet"
  chainId = 10

[[chains]]
  name = "Zora"
  chainId = 7777777
